# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50, verbose_name='Texto')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
            ],
        ),
    ]
