# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
